Loading underworld/2.13.0
  Loading requirement: python/3.10.4 petsc/3.17.1_openmpi libxml/2.9.12
No protocol specified
[3]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[3]PETSC ERROR: Argument out of range
[3]PETSC ERROR: New nonzero at (586,586) caused a malloc
Use MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE) to turn off this check
[3]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[3]PETSC ERROR: Petsc Release Version 3.17.1, Apr 28, 2022 
[3]PETSC ERROR: Pysklywec2000LikeCostantR.py on a  named node08 by nenglu Tue Apr 25 01:41:39 2023
[3]PETSC ERROR: Configure options --with-debugging=0 --COPTFLAGS="-g -O3" --CXXOPTFLAGS="-g -O3" --FOPTFLAGS="-g -O3" --prefix=/opt/cluster/software/petsc/petsc-3.17.1_openmpi --with-petsc4py=1 --with-zlib=1 --download-fblaslapack=1 --download-hdf5=1 --download-mumps=1 --download-parmetis=1 --download-metis=1 --download-superlu=1 --download-hypre=1 --download-scalapack=1 --download-superlu_dist=1 --download-ctetgen --download-eigen --download-triangle --useThreads=0 --download-superlu=1 --with-shared-libraries --with-cxx-dialect=C++11 --with-make-np=8
[3]PETSC ERROR: #1 MatSetValues_SeqAIJ() at /tmp/petsc-3.17.1/src/mat/impls/aij/seq/aij.c:478
[3]PETSC ERROR: #2 MatSetValues() at /tmp/petsc-3.17.1/src/mat/interface/matrix.c:1343
[3]PETSC ERROR: #3 MatDiagonalSet_Default() at /tmp/petsc-3.17.1/src/mat/utils/axpy.c:315
[3]PETSC ERROR: #4 MatDiagonalSet_SeqAIJ() at /tmp/petsc-3.17.1/src/mat/impls/aij/seq/aij.c:205
[3]PETSC ERROR: #5 MatDiagonalSet() at /tmp/petsc-3.17.1/src/mat/utils/axpy.c:355
[3]PETSC ERROR: #6 MatDiagonalSet_MPIAIJ() at /tmp/petsc-3.17.1/src/mat/impls/aij/mpi/mpiaij.c:164
[3]PETSC ERROR: #7 MatDiagonalSet() at /tmp/petsc-3.17.1/src/mat/utils/axpy.c:355
[3]PETSC ERROR: #8 MatGalerkin() at /tmp/petsc-3.17.1/src/mat/interface/matrix.c:10358
[3]PETSC ERROR: #9 PCSetUp_MG() at /tmp/petsc-3.17.1/src/ksp/pc/impls/mg/mg.c:1056
[3]PETSC ERROR: #10 PCSetUp() at /tmp/petsc-3.17.1/src/ksp/pc/interface/precon.c:990
[3]PETSC ERROR: #11 KSPSetUp() at /tmp/petsc-3.17.1/src/ksp/ksp/interface/itfunc.c:407
An uncaught exception was encountered on processor 3.
Traceback (most recent call last):
  File "/home/nenglu/Pysklywec2000LikeCostantR.py", line 446, in <module>
    Model.run_for(20.0 * u.megayears, checkpoint_interval=checkpoint_interval,dt= dt)
  File "/opt/cluster/software/underworld/2.13.0/lib/python3.10/site-packages/underworld/UWGeodynamics/_model.py", line 1675, in run_for
    self.solve()
  File "/opt/cluster/software/underworld/2.13.0/lib/python3.10/site-packages/underworld/UWGeodynamics/_model.py", line 1514, in solve
    self.solver.solve(
  File "/opt/cluster/software/underworld/2.13.0/lib/python3.10/site-packages/underworld/systems/_bsscr.py", line 450, in solve
    libUnderworld.StgFEM.SystemLinearEquations_ExecuteSolver(self._stokesSLE._cself, None)
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
An error was encountered during the PETSc solver setup. You should refer to the PETSc
error message for details. Note that if you are running within Jupyter, this error
message will only be visible in the console window.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 3 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
